/**
 * API Key API
 * Corresponds to backend /api/admin/api-keys route
 */

import { get, post, put, del } from './client';
import {
  ApiKey,
  ApiKeyCreate,
  ApiKeyUpdate,
  ApiKeyListParams,
  PaginatedResponse,
} from '@/types';

const BASE_URL = '/api/admin/api-keys';

/**
 * Get API Key List
 * @param params - Query parameters (pagination, status filtering)
 */
export async function getApiKeys(
  params?: ApiKeyListParams
): Promise<PaginatedResponse<ApiKey>> {
  return get<PaginatedResponse<ApiKey>>(BASE_URL, params as Record<string, unknown>);
}

/**
 * Get Single API Key Details
 * @param id - API Key ID
 */
export async function getApiKey(id: number): Promise<ApiKey> {
  return get<ApiKey>(`${BASE_URL}/${id}`);
}

/**
 * Get raw (unsanitized) key_value
 * @param id - API Key ID
 * @returns Raw key_value for viewing or copying
 */
export async function getRawKeyValue(id: number): Promise<string> {
  const response = await get<{ key_value: string }>(`${BASE_URL}/${id}/raw`);
  return response.key_value;
}

/**
 * Create API Key (key_value generated by backend)
 * @param data - Creation data (only key_name required)
 * @returns Complete API Key (includes full key_value, only once)
 */
export async function createApiKey(data: ApiKeyCreate): Promise<ApiKey> {
  return post<ApiKey>(BASE_URL, data);
}

/**
 * Update API Key
 * @param id - API Key ID
 * @param data - Update data (key_name, is_active)
 */
export async function updateApiKey(
  id: number,
  data: ApiKeyUpdate
): Promise<ApiKey> {
  return put<ApiKey>(`${BASE_URL}/${id}`, data);
}

/**
 * Delete API Key
 * @param id - API Key ID
 */
export async function deleteApiKey(id: number): Promise<void> {
  return del<void>(`${BASE_URL}/${id}`);
}
