"""
API Key Domain Model

Defines API Key related Data Transfer Objects (DTOs).
"""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class ApiKeyBase(BaseModel):
    """API Key Base Model"""
    
    # Key Name
    key_name: str = Field(..., min_length=1, max_length=100, description="Key Name")


class ApiKeyCreate(ApiKeyBase):
    """Create API Key Request Model"""
    pass
    # key_value is automatically generated by the backend, no need for client to provide


class ApiKeyUpdate(BaseModel):
    """Update API Key Request Model"""
    
    key_name: Optional[str] = Field(None, min_length=1, max_length=100)
    is_active: Optional[bool] = None


class ApiKeyModel(ApiKeyBase):
    """API Key Complete Model"""
    
    id: int = Field(..., description="API Key ID")
    key_value: str = Field(..., description="Key Value")
    is_active: bool = Field(True, description="Is Active")
    created_at: datetime = Field(..., description="Creation Time")
    last_used_at: Optional[datetime] = Field(None, description="Last Used Time")
    
    class Config:
        from_attributes = True


class ApiKeyResponse(ApiKeyBase):
    """API Key Response Model (key_value sanitized)"""
    
    id: int = Field(..., description="API Key ID")
    # key_value sanitized display
    key_value: str = Field(..., description="Key Value (Sanitized)")
    is_active: bool = Field(True, description="Is Active")
    created_at: datetime = Field(..., description="Creation Time")
    last_used_at: Optional[datetime] = Field(None, description="Last Used Time")
    
    class Config:
        from_attributes = True


class ApiKeyCreateResponse(ApiKeyBase):
    """Create API Key Response Model (key_value fully displayed, once only)"""
    
    id: int = Field(..., description="API Key ID")
    # Return full key_value on creation, not displayed afterwards
    key_value: str = Field(..., description="Key Value (Fully displayed only on creation)")
    is_active: bool = Field(True, description="Is Active")
    created_at: datetime = Field(..., description="Creation Time")
    last_used_at: Optional[datetime] = Field(None, description="Last Used Time")
    
    class Config:
        from_attributes = True