"""
API Key Management API

Provides CRUD endpoints for API Keys.
"""

from typing import Optional

from fastapi import APIRouter, Depends, Query, status
from fastapi.responses import JSONResponse
from pydantic import BaseModel

from app.api.deps import ApiKeyServiceDep, LogServiceDep, require_admin_auth
from app.common.errors import AppError
from app.domain.api_key import ApiKeyCreate, ApiKeyUpdate, ApiKeyResponse, ApiKeyCreateResponse

router = APIRouter(
    prefix="/admin/api-keys",
    tags=["Admin - API Keys"],
    dependencies=[Depends(require_admin_auth)],
)


class PaginatedApiKeyResponse(BaseModel):
    """API Key Pagination Response"""
    items: list[ApiKeyResponse]
    total: int
    page: int
    page_size: int


@router.get("", response_model=PaginatedApiKeyResponse)
async def list_api_keys(
    service: ApiKeyServiceDep,
    log_service: LogServiceDep,
    is_active: Optional[bool] = Query(None, description="Filter by active status"),
    page: int = Query(1, ge=1, description="Page number"),
    page_size: int = Query(20, ge=1, le=1000, description="Items per page"),
):
    """
    Get API Key list
    
    key_value will be sanitized.
    Includes current month's total cost for each API Key.
    """
    try:
        items, total = await service.get_all(is_active, page, page_size)
        
        # Get monthly costs for all API Keys in the result
        api_key_ids = [item.id for item in items]
        monthly_costs = await log_service.get_api_key_monthly_costs(api_key_ids)
        
        # Create a mapping from api_key_id to total_cost
        cost_map = {cost.api_key_id: cost.total_cost for cost in monthly_costs}
        
        # Update items with monthly_cost
        for item in items:
            item.monthly_cost = cost_map.get(item.id, 0.0)
        
        return PaginatedApiKeyResponse(
            items=items,
            total=total,
            page=page,
            page_size=page_size,
        )
    except AppError as e:
        return JSONResponse(content=e.to_dict(), status_code=e.status_code)


@router.get("/{key_id}", response_model=ApiKeyResponse)
async def get_api_key(
    key_id: int,
    service: ApiKeyServiceDep,
):
    """
    Get single API Key details

    key_value will be sanitized.
    """
    try:
        return await service.get_by_id(key_id)
    except AppError as e:
        return JSONResponse(content=e.to_dict(), status_code=e.status_code)


class RawKeyValueResponse(BaseModel):
    """Raw key_value response"""
    key_value: str


@router.get("/{key_id}/raw", response_model=RawKeyValueResponse)
async def get_raw_key_value(
    key_id: int,
    service: ApiKeyServiceDep,
):
    """
    Get raw (unsanitized) key_value

    Use this endpoint to retrieve the full API key for viewing or copying.
    """
    try:
        key_value = await service.get_raw_key_value(key_id)
        return RawKeyValueResponse(key_value=key_value)
    except AppError as e:
        return JSONResponse(content=e.to_dict(), status_code=e.status_code)


@router.post("", response_model=ApiKeyCreateResponse, status_code=status.HTTP_201_CREATED)
async def create_api_key(
    data: ApiKeyCreate,
    service: ApiKeyServiceDep,
):
    """
    Create API Key
    
    key_value is automatically generated by the system and returned fully ONLY upon creation.
    Please save the key_value securely as it cannot be retrieved in full again.
    """
    try:
        return await service.create(data)
    except AppError as e:
        return JSONResponse(content=e.to_dict(), status_code=e.status_code)


@router.put("/{key_id}", response_model=ApiKeyResponse)
async def update_api_key(
    key_id: int,
    data: ApiKeyUpdate,
    service: ApiKeyServiceDep,
):
    """
    Update API Key
    
    Can update name and active status.
    """
    try:
        return await service.update(key_id, data)
    except AppError as e:
        return JSONResponse(content=e.to_dict(), status_code=e.status_code)


@router.delete("/{key_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_api_key(
    key_id: int,
    service: ApiKeyServiceDep,
):
    """
    Delete API Key
    """
    try:
        await service.delete(key_id)
    except AppError as e:
        return JSONResponse(content=e.to_dict(), status_code=e.status_code)